Add simple manual pages.  Try to download map index at package install time.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -3,9 +3,40 @@
 
 set -e
 
+. /usr/share/debconf/confmodule
+
+indexdir=/var/lib/roadmap
+indexurl=http://roadmap.digitalomaha.net/maps/usdir.rdm.tgz
+
+
+# Fetch usdir.rdm and make it available for all users
+update_map_index() {
+    umask 022
+    mkdir -p $indexdir
+    cd $indexdir
+    # Fetch and unpack the new map index
+    echo "info: Downloading $indexurl"
+    if wget -O - $indexurl 2> /dev/null |
+	tar zxf - usdir.rdm 2> /dev/null; then
+	chmod 644 usdir.rdm
+    else
+	echo "error: Unable to download map index."
+    fi
+}
+
 case "$1" in
     configure)
         if [ -x /usr/bin/update-menus ] ; then update-menus ; fi
+
+	# Ask if the map index file should be downloaded
+	if [ ! -f "$indexdir/usdir.rdm" ] ; then
+	    db_input medium roadmap/download_index || [ $? -eq 30 ]
+	    db_go
+	    db_get roadmap/download_index
+	    if [ true = "$RET" ] ; then
+		update_map_index
+	    fi
+	fi
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
